FROM golang:1.27.1-alpine3.23@sha256:d9e2f2f07b10cc922da3e80e035c3058810b328d5aef82d2c63680967c5e2ec9 AS builder

ARG CADDY_VERSION=v2.11.4
ARG X_CRYPTO_VERSION=v0.55.0
ARG X_NET_VERSION=v0.57.0
ARG X_TEXT_VERSION=v0.41.0
ARG GRPC_VERSION=v1.83.1
ENV CGO_ENABLED=0

COPY scripts/collect-go-licenses.sh /usr/local/bin/collect-go-licenses.sh

RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    mkdir -p /build /licenses/caddy \
    && cd /build \
    && go mod init recipes-caddy \
    && go get \
      "github.com/caddyserver/caddy/v2@${CADDY_VERSION}" \
      "golang.org/x/crypto@${X_CRYPTO_VERSION}" \
      "golang.org/x/net@${X_NET_VERSION}" \
      "golang.org/x/text@${X_TEXT_VERSION}" \
      "google.golang.org/grpc@${GRPC_VERSION}" \
    && go mod download all \
    && go build -trimpath \
      -ldflags="-s -w -X github.com/caddyserver/caddy/v2.CustomVersion=${CADDY_VERSION}" \
      -o /go/bin/caddy github.com/caddyserver/caddy/v2/cmd/caddy \
    && /go/bin/caddy version \
    && cp "$(go env GOPATH)/pkg/mod/github.com/caddyserver/caddy/v2@${CADDY_VERSION}/LICENSE" \
      /licenses/caddy/LICENSE \
    && sh /usr/local/bin/collect-go-licenses.sh /licenses/go-modules

FROM alpine:3.23.5@sha256:fd791d74b68913cbb027c6546007b3f0d3bc45125f797758156952bc2d6daf40 AS runtime-files

RUN apk upgrade --no-cache \
    && apk add --no-cache ca-certificates tzdata \
    && addgroup --system --gid 10001 caddy \
    && adduser --system --disabled-password --no-create-home \
      --uid 10001 --ingroup caddy caddy \
    && mkdir -p /config/caddy /data/caddy /etc/caddy /srv \
    && chown -R 10001:10001 /config /data /etc/caddy /srv

FROM scratch

LABEL org.opencontainers.image.source="https://github.com/phinaldoo/recipes" \
      org.opencontainers.image.version="2.11.4" \
      org.opencontainers.image.licenses="Apache-2.0"

ENV XDG_CONFIG_HOME=/config \
    XDG_DATA_HOME=/data

COPY --from=runtime-files /etc/passwd /etc/passwd
COPY --from=runtime-files /etc/group /etc/group
COPY --from=runtime-files /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=runtime-files /usr/share/zoneinfo /usr/share/zoneinfo
COPY --from=runtime-files --chown=10001:10001 /config /config
COPY --from=runtime-files --chown=10001:10001 /data /data
COPY --from=runtime-files --chown=10001:10001 /etc/caddy /etc/caddy
COPY --from=runtime-files --chown=10001:10001 /srv /srv
COPY --from=builder /go/bin/caddy /usr/bin/caddy
COPY --from=builder /licenses /licenses

USER 10001:10001
WORKDIR /srv

EXPOSE 8080

ENTRYPOINT ["/usr/bin/caddy"]
CMD ["run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile"]
